export default [
  "Probably subscribed to Dalux",
  "Bozo", 
  "You fell off", 
  "You're\*", 
  "Genshinner",
  "Take a shower",
  "💀",
  "Das why yo momma ded",
  "Ratio^2",
  "L",
  "Seethe",
  "Mald",
  "Cope",
  "2 Followers",
  "Source?",
  "Go Outside",
  "Any Askers?",
  "Beaned",
  "Admin-chan isn't real",
  "Not funny, didn't laugh",
  "Banned",
  "Skill Issue",
  "Marwan's Idea",
  "eateing chips chrongch cronc mm",
  "Dalux Blob",
  "Yamm did it better",
  "Ratio failure",
  "DND on",
  "Take a bath",
  "Probably doesn't listen to Creo",
  "Anime pfp",
  "Can't join VIP vc",
  "Omelette eater",
  "ok and?",
  "touch grass",
  "dosen't follow Dalux News",
  "cancelled on Dalux News",
  "cancelled on Twitter dot com",
  "bonk",
  "Blocked",
  "Banned",
  "Reported",
  "Uncollabed",
  "Unfollowed"
]